export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST"
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS"
export const GET_STATUS_FAIL = "GET_STATUS_FAIL"

export const ADD_STATUS_REQUEST = "ADD_STATUS_REQUEST"
export const ADD_STATUS_SUCCESS = "ADD_STATUS_SUCCESS"
export const ADD_STATUS_FAIL = "ADD_STATUS_FAIL"

export const DELETE_STATUS_REQUEST = "DELETE_STATUS_REQUEST"
export const DELETE_STATUS_SUCCESS = "DELETE_STATUS_SUCCESS"
export const DELETE_STATUS_FAIL = "DELETE_STATUS_FAIL"

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST"
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS"
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL"


